version: '3'
services:
    test-fullstack-java-service:
        build: ./
        image: adamspay-integration:1.0.0
        container_name: adamspay-integration
        ports:
        - "8080:8080"
        volumes:
        - ./logs:/logs
    test-fullstack-java-db-service:
        container_name: adamspaydb
        image: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-myuser}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
            POSTGRES_DB: testdb
