# fly.toml app configuration file generated for adamspay-integration on 2023-08-01T10:21:27-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "adamspay-integration"
primary_region = "eze"

[build]

[http_service]
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
