spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://adamspaydb:5432/adamspaydb
    username: myuser
    password: secret
    platform: postgres
    #initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: false
#    generate-ddl: false
    hibernate:
     ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false;
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  #      dialect: org.hibernate.dialect.MySQL5Dialect

  queries:
    users-query: select email, password, active from users where email=?
    roles-query: select email, role from users where email=?
server:
  servlet:
    contextPath: /

jwtSecret: secret0key0for0encryptionsecret0key0for0encryptionsecret0key0for0encryption
jwtExpiration: 6000000

adamspay:
  apikey: ap-6e18d9ac69f7bb175ba6a9d9